### ISSUE TITLE
Cursor should turn into link click style when hovering |Copy| over branch

### ISSUE THREAD

**Issue by nikitabobko** [igoriakovlev/TeamCity-Test-Name-Copy-2-Clipboard#2]
ACT:
![image](https://user-images.githubusercontent.com/20517828/129069827-e215d042-b9d4-4ac9-aaae-16c8b7f42be5.png)
EXP:
![image](https://user-images.githubusercontent.com/20517828/129069902-96fd23d4-5dda-4e73-b595-dec979bfbf88.png)

**Comment by nikitabobko** [comment]
@igoriakovlev please take a look ASAP

**Comment by nikitabobko** [comment]
Without this feature the extension is totally unusable

**Comment by igoriakovlev** [comment]
@nikitabobko 
Nice job, @nikitabobko, thank you for discovering this critical issue.
Fixed instantly!
